# ram_test.xdc — reloj de 50 MHz + LEDs (subconjunto de ../zynq_mini.xdc)
set_property PACKAGE_PIN K17      [get_ports clk]
set_property IOSTANDARD  LVCMOS33 [get_ports clk]
create_clock -period 20.000 -name sys_clk [get_ports clk]
set_property PACKAGE_PIN W13      [get_ports {led[0]}]
set_property PACKAGE_PIN V12      [get_ports {led[1]}]
set_property PACKAGE_PIN U12      [get_ports {led[2]}]
set_property PACKAGE_PIN T12      [get_ports {led[3]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {led[*]}]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
