/* xparameters.h — a mano (sin SDK) para el FSBL del MSXimus en la ZYNQ MINI.
 * Lo que necesitan el FSBL de Xilinx (zynq_fsbl 2019.2), la BSP standalone y los
 * drivers qspips / sdps / devcfg / xilffs. Direcciones del TRM del Zynq-7000. */
#ifndef XPARAMETERS_H
#define XPARAMETERS_H
#include "xparameters_ps.h"

#define XPAR_CPU_ID 0U
#define XPAR_CPU_CORTEXA9_0_CPU_CLK_FREQ_HZ 666666687U
#define XPAR_CPU_CORTEXA9_CORE_CLOCK_FREQ_HZ 666666687U
#define XPAR_PS7_DDR_0_S_AXI_BASEADDR 0x00100000U
#define XPAR_PS7_DDR_0_S_AXI_HIGHADDR 0x1FFFFFFFU
#define XPAR_PS7_RAM_0_S_AXI_BASEADDR 0x00000000U
#define XPAR_PS7_RAM_0_S_AXI_HIGHADDR 0x0003FFFFU
#define XPAR_PS7_RAM_1_S_AXI_BASEADDR 0xFFFF0000U
#define XPAR_PS7_RAM_1_S_AXI_HIGHADDR 0xFFFFFDFFU

/* Timer global del Cortex-A9 (usleep, XTime): CPU/2 */
#define XPAR_GLOBAL_TMR_BASEADDR 0xF8F00200U
#define XPAR_GLOBAL_TMR_INTR 27U
#define COUNTS_PER_SECOND (XPAR_CPU_CORTEXA9_0_CPU_CLK_FREQ_HZ / 2U)

/* Consola: UART1 (MIO 48/49 -> CH340 del P1), 115200 8N1 por ps7_init */
#define XPAR_XUARTPS_NUM_INSTANCES 1
#define XPAR_XUARTPS_0_DEVICE_ID 0
#define XPAR_XUARTPS_0_BASEADDR 0xE0001000U
#define XPAR_XUARTPS_0_HIGHADDR 0xE0001FFFU
#define XPAR_XUARTPS_0_UART_CLK_FREQ_HZ 100000000U
#define XPAR_PS7_UART_1_BASEADDR 0xE0001000U
#define STDOUT_BASEADDRESS 0xE0001000U
#define STDIN_BASEADDRESS 0xE0001000U

/* DevCfg / PCAP (carga del bitstream) */
#define XPAR_XDCFG_NUM_INSTANCES 1
#define XPAR_XDCFG_0_DEVICE_ID 0
#define XPAR_XDCFG_0_BASEADDR 0xF8007000U
#define XPAR_XDCFG_0_HIGHADDR 0xF80070FFU
#define XPAR_PS7_DEV_CFG_0_DEVICE_ID 0

/* QSPI (U15, 16 MB, MIO 1..6, una sola flash x4). El BootROM lo deja configurado en modo QSPI */
#define XPAR_XQSPIPS_NUM_INSTANCES 1
#define XPAR_XQSPIPS_0_DEVICE_ID 0
#define XPAR_XQSPIPS_0_BASEADDR 0xE000D000U
#define XPAR_XQSPIPS_0_HIGHADDR 0xE000DFFFU
#define XPAR_XQSPIPS_0_QSPI_CLK_FREQ_HZ 200000000U
#define XPAR_XQSPIPS_0_QSPI_MODE 0
#define XPAR_XQSPIPS_0_QSPI_BUS_WIDTH 2
#define XPAR_PS7_QSPI_0_DEVICE_ID 0
#define XPAR_PS7_QSPI_LINEAR_0_S_AXI_BASEADDR 0xFC000000U
#define XPAR_PS7_QSPI_LINEAR_0_S_AXI_HIGHADDR 0xFCFFFFFFU

/* SDIO: 0 = TF1 (SD0, MIO 40..45, banco 1) = la tarjeta de BOOT.bin; 1 = TF2 (SD1) */
#define XPAR_XSDPS_NUM_INSTANCES 2
#define XPAR_XSDPS_0_DEVICE_ID 0
#define XPAR_XSDPS_0_BASEADDR 0xE0100000U
#define XPAR_XSDPS_0_SDIO_CLK_FREQ_HZ 50000000U
#define XPAR_XSDPS_0_HAS_CD 0
#define XPAR_XSDPS_0_HAS_WP 0
#define XPAR_XSDPS_0_BUS_WIDTH 0
#define XPAR_XSDPS_0_MIO_BANK 1
#define XPAR_XSDPS_0_HAS_EMIO 0
#define XPAR_XSDPS_0_IS_CACHE_COHERENT 0
#define XPAR_XSDPS_1_DEVICE_ID 1
#define XPAR_XSDPS_1_BASEADDR 0xE0101000U
#define XPAR_XSDPS_1_SDIO_CLK_FREQ_HZ 50000000U
#define XPAR_XSDPS_1_HAS_CD 0
#define XPAR_XSDPS_1_HAS_WP 0
#define XPAR_XSDPS_1_BUS_WIDTH 0
#define XPAR_XSDPS_1_MIO_BANK 0
#define XPAR_XSDPS_1_HAS_EMIO 0
#define XPAR_XSDPS_1_IS_CACHE_COHERENT 0
#define XPAR_PS7_SD_0_DEVICE_ID XPAR_XSDPS_0_DEVICE_ID
#define XPAR_PS7_SD_0_S_AXI_BASEADDR 0xE0100000U
#define XPAR_PS7_SD_1_DEVICE_ID XPAR_XSDPS_1_DEVICE_ID

/* xilffs (FatFs) como lo configura el SDK para el FSBL: solo lectura, sin LFN */
#define FILE_SYSTEM_INTERFACE_SD
#define FILE_SYSTEM_READ_ONLY
#define FILE_SYSTEM_USE_LFN 0
#define FILE_SYSTEM_USE_STRFUNC 0
#define FILE_SYSTEM_SET_FS_RPATH 0
#define FILE_SYSTEM_NUM_LOGIC_VOL 2
#define FILE_SYSTEM_WORD_ACCESS

#endif
