/* xsdps_g.c — tabla de configuracion de los dos SDIO del Zynq (a mano, sin SDK). */
#include "xparameters.h"
#include "xsdps.h"

XSdPs_Config XSdPs_ConfigTable[XPAR_XSDPS_NUM_INSTANCES] = {
    { XPAR_XSDPS_0_DEVICE_ID, XPAR_XSDPS_0_BASEADDR, XPAR_XSDPS_0_SDIO_CLK_FREQ_HZ,
      XPAR_XSDPS_0_HAS_CD, XPAR_XSDPS_0_HAS_WP, XPAR_XSDPS_0_BUS_WIDTH, XPAR_XSDPS_0_MIO_BANK,
      XPAR_XSDPS_0_HAS_EMIO, XPAR_XSDPS_0_IS_CACHE_COHERENT },
    { XPAR_XSDPS_1_DEVICE_ID, XPAR_XSDPS_1_BASEADDR, XPAR_XSDPS_1_SDIO_CLK_FREQ_HZ,
      XPAR_XSDPS_1_HAS_CD, XPAR_XSDPS_1_HAS_WP, XPAR_XSDPS_1_BUS_WIDTH, XPAR_XSDPS_1_MIO_BANK,
      XPAR_XSDPS_1_HAS_EMIO, XPAR_XSDPS_1_IS_CACHE_COHERENT }
};
