/* xparameters.h — a mano (sin SDK) para el proxy de SD del MSXimus en la ZYNQ MINI.
 * Solo lo que necesitan el driver xsdps (sdps_v3_8) y la BSP standalone minima. */
#ifndef XPARAMETERS_H
#define XPARAMETERS_H

#define XPAR_CPU_ID 0U
#define XPAR_CPU_CORTEXA9_0_CPU_CLK_FREQ_HZ 666666687U
#define XPAR_CPU_CORTEXA9_CORE_CLOCK_FREQ_HZ 666666687U
#define XPAR_PS7_DDR_0_S_AXI_BASEADDR 0x00100000U
#define XPAR_PS7_DDR_0_S_AXI_HIGHADDR 0x1FFFFFFFU
#define XPAR_PS7_RAM_0_S_AXI_BASEADDR 0x00000000U
#define XPAR_PS7_RAM_0_S_AXI_HIGHADDR 0x0003FFFFU

/* Timer global del Cortex-A9 (usleep): CPU/2 */
#define XPAR_GLOBAL_TMR_BASEADDR 0xF8F00200U
#define XPAR_GLOBAL_TMR_INTR 27U
#define COUNTS_PER_SECOND (XPAR_CPU_CORTEXA9_0_CPU_CLK_FREQ_HZ / 2U)

/* SDIO: 0 = TF1 (SD0, MIO 40..45, banco 1), 1 = TF2 (SD1, MIO 10..15, banco 0) */
#define XPAR_XSDPS_NUM_INSTANCES 2
#define XPAR_XSDPS_0_DEVICE_ID 0
#define XPAR_XSDPS_0_BASEADDR 0xE0100000U
#define XPAR_XSDPS_0_SDIO_CLK_FREQ_HZ 50000000U
#define XPAR_XSDPS_0_HAS_CD 0
#define XPAR_XSDPS_0_HAS_WP 0
#define XPAR_XSDPS_0_BUS_WIDTH 0
#define XPAR_XSDPS_0_MIO_BANK 1
#define XPAR_XSDPS_0_HAS_EMIO 0
#define XPAR_XSDPS_0_IS_CACHE_COHERENT 0
#define XPAR_XSDPS_1_DEVICE_ID 1
#define XPAR_XSDPS_1_BASEADDR 0xE0101000U
#define XPAR_XSDPS_1_SDIO_CLK_FREQ_HZ 50000000U
#define XPAR_XSDPS_1_HAS_CD 0
#define XPAR_XSDPS_1_HAS_WP 0
#define XPAR_XSDPS_1_BUS_WIDTH 0
#define XPAR_XSDPS_1_MIO_BANK 0
#define XPAR_XSDPS_1_HAS_EMIO 0
#define XPAR_XSDPS_1_IS_CACHE_COHERENT 0

#define XPAR_PS7_SD_0_DEVICE_ID XPAR_XSDPS_0_DEVICE_ID
#define XPAR_PS7_SD_1_DEVICE_ID XPAR_XSDPS_1_DEVICE_ID

/* SLCR (xplatform_info / tap delays) */
#define XPS_SYS_CTRL_BASEADDR 0xF8000000U

#endif
